# Generated by Django 5.2.3 on 2025-06-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnos',
            options={'ordering': ['-created'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='carrera',
            field=models.TextField(verbose_name='carr'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='mat'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.TextField(verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='turno',
            field=models.CharField(max_length=10, verbose_name='tur'),
        ),
    ]
