# Generated by Django 4.2.23 on 2025-07-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='mat'),
        ),
    ]
